Fix NullReferenceException
itext/itextsharp pull request #34
Opened 2018-02-23 10:10 UTC by jorgemiguelmoreira

Throws NullRefenceException calling method ImageRenderInfo CreateForXObject(GraphicsState gs, PdfIndirectReference refi, PdfDictionary colorSpaceDictionary) because the last argument is null.

2018-11-19 16:57 UTC, Danghor requested changes
I would recommend using the null-propagator to make the code more concise.

2018-11-19 16:57 UTC, Danghor commented on src/core/iTextSharp/text/pdf/parser/ImageRenderInfo.cs
> +            if (markedContentInfos != null && markedContentInfos.Count > 0) { // check for performance purposes, as markedContentInfo.GetEnumerator is a costly operation for some reason
```suggestion
            if (markedContentInfos?.Count > 0) { // check for performance purposes, as markedContentInfo.GetEnumerator is a costly operation for some reason
```

2018-11-19 16:57 UTC, Danghor commented on src/core/iTextSharp/text/pdf/parser/ImageRenderInfo.cs
> +            if (markedContentInfos != null && markedContentInfos.Count > 0) { // check for performance purposes, as markedContentInfo.GetEnumerator is a costly operation for some reason
```suggestion
            if (markedContentInfos?.Count > 0) { // check for performance purposes, as markedContentInfo.GetEnumerator is a costly operation for some reason
```

2019-02-22 10:05 UTC, ar3em commented
@jorgemiguelmoreira Thank you for this correcting. Your changes accepted and added to project.

2019-02-22 10:54 UTC, ar3em commented
@jorgemiguelmoreira Thank you for this correcting. Your changes accepted and PR was merged manually.

2019-02-22 14:15 UTC, closed without merging